all: Room Object TextAdventure TextAdventureGame

Room: Room.java
	javac Room.java

Object: Object.java
	javac Object.java

TextAdventure: TextAdventure.java
	javac TextAdventure.java

TextAdventureGame: TextAdventureGame.java
	javac TextAdventureGame.java

.PHONY: clean
clean:
	rm -rf Object.class; rm -rf Room.class; rm -rf TextAdventure.class; rm -rf TextAdventureGame.class
