cc_test(
	name="posedge_trigger_test",
	srcs=["util/posedge_trigger.cpp","util/posedge_trigger.h"],
	copts=["-DPOSEDGE_TRIGGER_TEST"],
	deps=[],
	timeout="short"
)

cc_test(
	name="point_test",
	srcs=["util/point.cpp","util/point.h"],
	deps=[],
	copts=["-DPOINT_TEST"],
	timeout="short"
)